<template><h3 id="_6、异步加载js的方式有哪些-会阻塞什么" tabindex="-1"><a class="header-anchor" href="#_6、异步加载js的方式有哪些-会阻塞什么" aria-hidden="true">#</a> 6、异步加载JS的方式有哪些？会阻塞什么？</h3>
<p><strong>常用方法</strong></p>
<p>1、在<code>&lt;script&gt;</code>标签中添加defer属性，允许只写属性名省略属性值。将在DOM构建完毕之后onload之前执行，不会阻塞DOM树构建，但会阻塞onload的执行。</p>
<p>2、在<code>&lt;script&gt;</code>标签中添加async属性，允许只写属性名省略属性值。将在onload时启用浏览器的另一个进程执行，不会阻塞DOM树构建，也不会阻塞onload的执行。此属性为H5的新特性，支持H5的浏览器都支持async属性。</p>
<div class="language-html ext-html line-numbers-mode"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>script</span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>text/javascript<span class="token punctuation">"</span></span> <span class="token attr-name">defer</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>defer<span class="token punctuation">"</span></span> <span class="token attr-name">src</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>/index.js<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token script"></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>script</span><span class="token punctuation">></span></span>

<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>script</span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>text/javascript<span class="token punctuation">"</span></span> <span class="token attr-name">async</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>async<span class="token punctuation">"</span></span> <span class="token attr-name">src</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>/index.js<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token script"></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>script</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><p>3、动态创建脚本。此方式在onload阶段启用浏览器的另一个进程执行，不会阻塞DOM树构建，也不会阻塞onload的执行。所有浏览器都支持。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">function</span> <span class="token function">addScriptTag</span><span class="token punctuation">(</span><span class="token parameter">src</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
	<span class="token keyword">var</span> script <span class="token operator">=</span> document<span class="token punctuation">.</span><span class="token function">createElement</span><span class="token punctuation">(</span><span class="token string">'script'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
	script<span class="token punctuation">.</span><span class="token function">setAttribute</span><span class="token punctuation">(</span><span class="token string">"type"</span><span class="token punctuation">,</span> <span class="token string">"text/javascript"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
	script<span class="token punctuation">.</span>src <span class="token operator">=</span> src<span class="token punctuation">;</span>
	document<span class="token punctuation">.</span>body<span class="token punctuation">.</span><span class="token function">appendChild</span><span class="token punctuation">(</span>script<span class="token punctuation">)</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br></div></div><p><strong>其他方法</strong></p>
<ul>
<li>XHR Eval，通过传统的Ajax方式，用XMLHttpRequest（低版本IE中是ActiveXObject）异步获得脚本内容后，通过eval执行脚本</li>
<li>XHR Inject，用传统Ajax方式下载脚本后，不再通过eval，而是动态创建script元素后塞进页面</li>
<li>Script in iframe，利用iframe可以和其他组件并行下载的特性，将脚本嵌入到iframe里实现异步加载。缺点同样是不能跨越，脚本和页面必须在同一个域中。</li>
<li>document.write Script，在IE中可以用document.write把script元素写入HTML可以实现并行下载脚本，但下载脚本时仍旧会对其他资源造成脚本阻塞</li>
</ul>
</template>
